// Common country name → exchange/country codes mapping
const COUNTRY_MAP: Record<string, string[]> = {
  "FRANCE": ["FR", "FP", "PA"],
  "USA": ["US", "UN", "UW", "UA", "UQ"],
  "UNITED STATES": ["US", "UN", "UW", "UA", "UQ"],
  "ETATS-UNIS": ["US", "UN", "UW", "UA", "UQ"],
  "UK": ["LN", "GB", "L"],
  "UNITED KINGDOM": ["LN", "GB", "L"],
  "ROYAUME-UNI": ["LN", "GB", "L"],
  "ANGLETERRE": ["LN", "GB", "L"],
  "GERMANY": ["GR", "GY", "DE", "GF"],
  "ALLEMAGNE": ["GR", "GY", "DE", "GF"],
  "SWITZERLAND": ["SW", "SE", "CH", "VX"],
  "SUISSE": ["SW", "SE", "CH", "VX"],
  "JAPAN": ["JT", "JP"],
  "JAPON": ["JT", "JP"],
  "CHINA": ["CH", "CN", "HK", "SS", "SZ"],
  "CHINE": ["CH", "CN", "HK", "SS", "SZ"],
  "CANADA": ["CT", "CA", "CN"],
  "AUSTRALIA": ["AT", "AU"],
  "AUSTRALIE": ["AT", "AU"],
  "ITALY": ["IM", "IT"],
  "ITALIE": ["IM", "IT"],
  "SPAIN": ["SM", "ES", "MC"],
  "ESPAGNE": ["SM", "ES", "MC"],
  "NETHERLANDS": ["NA", "NL"],
  "PAYS-BAS": ["NA", "NL"],
  "BELGIUM": ["BB", "BE"],
  "BELGIQUE": ["BB", "BE"],
  "BRAZIL": ["BZ", "BR"],
  "BRESIL": ["BZ", "BR"],
  "INDIA": ["IB", "IN", "IS"],
  "INDE": ["IB", "IN", "IS"],
  "SOUTH AFRICA": ["SJ", "ZA"],
  "AFRIQUE DU SUD": ["SJ", "ZA"],
  "MAURITIUS": ["MP", "MU"],
  "MAURICE": ["MP", "MU"],
  "SINGAPORE": ["SP", "SG"],
  "SINGAPOUR": ["SP", "SG"],
  "HONG KONG": ["HK"],
  "SWEDEN": ["SS", "SE"],
  "SUEDE": ["SS", "SE"],
  "NORWAY": ["NO", "OL"],
  "NORVEGE": ["NO", "OL"],
  "DENMARK": ["DC", "DK"],
  "DANEMARK": ["DC", "DK"],
  "FINLAND": ["FH", "FI"],
  "FINLANDE": ["FH", "FI"],
  "AUSTRIA": ["AV", "AT"],
  "AUTRICHE": ["AV", "AT"],
  "PORTUGAL": ["PL", "PT"],
  "IRELAND": ["ID", "IE"],
  "IRLANDE": ["ID", "IE"],
  "MEXICO": ["MM", "MX"],
  "MEXIQUE": ["MM", "MX"],
  "SOUTH KOREA": ["KS", "KR"],
  "COREE DU SUD": ["KS", "KR"],
  "TAIWAN": ["TT", "TW"],
  "RUSSIA": ["RU", "RM"],
  "RUSSIE": ["RU", "RM"],
  "POLAND": ["PW", "PL"],
  "POLOGNE": ["PW", "PL"],
  "TURKEY": ["TI", "TR"],
  "TURQUIE": ["TI", "TR"],
  "INDONESIA": ["IJ", "ID"],
  "INDONESIE": ["IJ", "ID"],
  "MALAYSIA": ["MK", "MY"],
  "MALAISIE": ["MK", "MY"],
  "THAILAND": ["TB", "TH"],
  "THAILANDE": ["TB", "TH"],
  "PHILIPPINES": ["PM", "PH"],
  "VIETNAM": ["VN"],
  "NIGERIA": ["NL", "NG"],
  "EGYPT": ["EY", "EG"],
  "EGYPTE": ["EY", "EG"],
  "KENYA": ["KN", "KE"],
  "MOROCCO": ["MC", "MA"],
  "MAROC": ["MC", "MA"],
  "TUNISIA": ["TU", "TN"],
  "TUNISIE": ["TU", "TN"],
  "COTE D'IVOIRE": ["CI"],
  "SENEGAL": ["SN"],
  "GHANA": ["GH", "GN"],
  "LUXEMBOURG": ["LX", "LU"],
  "GREECE": ["GA", "GR"],
  "GRECE": ["GA", "GR"],
  "CZECH REPUBLIC": ["CP", "CZ"],
  "REPUBLIQUE TCHEQUE": ["CP", "CZ"],
  "HUNGARY": ["HB", "HU"],
  "HONGRIE": ["HB", "HU"],
  "ROMANIA": ["RO"],
  "ROUMANIE": ["RO"],
  "ARGENTINA": ["AR"],
  "ARGENTINE": ["AR"],
  "CHILE": ["CI", "CL"],
  "CHILI": ["CI", "CL"],
  "COLOMBIA": ["CB", "CO"],
  "COLOMBIE": ["CB", "CO"],
  "PERU": ["PE"],
  "PEROU": ["PE"],
  "SAUDI ARABIA": ["AB", "SA"],
  "ARABIE SAOUDITE": ["AB", "SA"],
  "UAE": ["UH", "AE"],
  "EMIRATS ARABES UNIS": ["UH", "AE"],
  "QATAR": ["QD", "QA"],
  "KUWAIT": ["KK", "KW"],
  "KOWEIT": ["KK", "KW"],
  "ISRAEL": ["IT", "IL"],
  "NEW ZEALAND": ["NZ"],
  "NOUVELLE-ZELANDE": ["NZ"],
  "PAKISTAN": ["PK"],
  "BANGLADESH": ["BD"],
  "SRI LANKA": ["LK"],
  "CONGO": ["CG", "CD"],
  "CAMEROON": ["CM"],
  "CAMEROUN": ["CM"],
};

export function getCountryCodes(query: string): string[] {
  const q = query.trim().toUpperCase();
  
  // Direct match
  if (COUNTRY_MAP[q]) return COUNTRY_MAP[q];
  
  // Partial match
  const matches: string[] = [];
  for (const [name, codes] of Object.entries(COUNTRY_MAP)) {
    if (name.includes(q) || q.includes(name)) {
      matches.push(...codes);
    }
  }
  
  // If input is already a 2-letter code, include it
  if (q.length === 2) matches.push(q);
  
  return [...new Set(matches)];
}
