// Common country name → exchange/country codes mapping
const COUNTRY_MAP: Record<string, string[]> = {
  // ─── Americas ───
  "USA": ["US", "UN", "UW", "UA", "UQ"],
  "UNITED STATES": ["US", "UN", "UW", "UA", "UQ"],
  "ETATS-UNIS": ["US", "UN", "UW", "UA", "UQ"],
  "CANADA": ["CT", "CA", "CN"],
  "MEXICO": ["MM", "MX"],
  "MEXIQUE": ["MM", "MX"],
  "BRAZIL": ["BZ", "BR"],
  "BRESIL": ["BZ", "BR"],
  "ARGENTINA": ["AR"],
  "ARGENTINE": ["AR"],
  "CHILE": ["CI", "CL"],
  "CHILI": ["CI", "CL"],
  "COLOMBIA": ["CB", "CO"],
  "COLOMBIE": ["CB", "CO"],
  "PERU": ["PE"],
  "PEROU": ["PE"],
  "VENEZUELA": ["VE"],
  "URUGUAY": ["UY"],
  "ECUADOR": ["EC"],
  "EQUATEUR": ["EC"],
  "PANAMA": ["PA"],
  "COSTA RICA": ["CR"],
  "JAMAICA": ["JM"],
  "JAMAIQUE": ["JM"],
  "TRINIDAD AND TOBAGO": ["TT"],
  "TRINITE ET TOBAGO": ["TT"],

  // ─── Europe ───
  "FRANCE": ["FR", "FP", "PA"],
  "UK": ["LN", "GB", "L"],
  "UNITED KINGDOM": ["LN", "GB", "L"],
  "ROYAUME-UNI": ["LN", "GB", "L"],
  "ANGLETERRE": ["LN", "GB", "L"],
  "GERMANY": ["GR", "GY", "DE", "GF"],
  "ALLEMAGNE": ["GR", "GY", "DE", "GF"],
  "SWITZERLAND": ["SW", "SE", "CH", "VX"],
  "SUISSE": ["SW", "SE", "CH", "VX"],
  "ITALY": ["IM", "IT"],
  "ITALIE": ["IM", "IT"],
  "SPAIN": ["SM", "ES", "MC"],
  "ESPAGNE": ["SM", "ES", "MC"],
  "NETHERLANDS": ["NA", "NL"],
  "PAYS-BAS": ["NA", "NL"],
  "BELGIUM": ["BB", "BE"],
  "BELGIQUE": ["BB", "BE"],
  "SWEDEN": ["SS", "SE"],
  "SUEDE": ["SS", "SE"],
  "NORWAY": ["NO", "OL"],
  "NORVEGE": ["NO", "OL"],
  "DENMARK": ["DC", "DK"],
  "DANEMARK": ["DC", "DK"],
  "FINLAND": ["FH", "FI"],
  "FINLANDE": ["FH", "FI"],
  "AUSTRIA": ["AV", "AT"],
  "AUTRICHE": ["AV", "AT"],
  "PORTUGAL": ["PL", "PT"],
  "IRELAND": ["ID", "IE"],
  "IRLANDE": ["ID", "IE"],
  "LUXEMBOURG": ["LX", "LU"],
  "GREECE": ["GA", "GR"],
  "GRECE": ["GA", "GR"],
  "CZECH REPUBLIC": ["CP", "CZ"],
  "REPUBLIQUE TCHEQUE": ["CP", "CZ"],
  "HUNGARY": ["HB", "HU"],
  "HONGRIE": ["HB", "HU"],
  "ROMANIA": ["RO"],
  "ROUMANIE": ["RO"],
  "POLAND": ["PW", "PL"],
  "POLOGNE": ["PW", "PL"],
  "RUSSIA": ["RU", "RM"],
  "RUSSIE": ["RU", "RM"],
  "TURKEY": ["TI", "TR"],
  "TURQUIE": ["TI", "TR"],
  "UKRAINE": ["UA", "UK"],
  "CROATIA": ["HR"],
  "CROATIE": ["HR"],
  "SERBIA": ["RS"],
  "SERBIE": ["RS"],
  "BULGARIA": ["BG"],
  "BULGARIE": ["BG"],
  "SLOVAKIA": ["SK"],
  "SLOVAQUIE": ["SK"],
  "SLOVENIA": ["SI"],
  "SLOVENIE": ["SI"],
  "ESTONIA": ["EE"],
  "ESTONIE": ["EE"],
  "LATVIA": ["LV"],
  "LETTONIE": ["LV"],
  "LITHUANIA": ["LT"],
  "LITUANIE": ["LT"],
  "ICELAND": ["IS"],
  "ISLANDE": ["IS"],
  "CYPRUS": ["CY"],
  "CHYPRE": ["CY"],
  "MALTA": ["MT"],
  "MALTE": ["MT"],

  // ─── Asia-Pacific ───
  "JAPAN": ["JT", "JP"],
  "JAPON": ["JT", "JP"],
  "CHINA": ["CH", "CN", "HK", "SS", "SZ"],
  "CHINE": ["CH", "CN", "HK", "SS", "SZ"],
  "HONG KONG": ["HK"],
  "INDIA": ["IB", "IN", "IS"],
  "INDE": ["IB", "IN", "IS"],
  "SOUTH KOREA": ["KS", "KR"],
  "COREE DU SUD": ["KS", "KR"],
  "TAIWAN": ["TT", "TW"],
  "AUSTRALIA": ["AT", "AU"],
  "AUSTRALIE": ["AT", "AU"],
  "NEW ZEALAND": ["NZ"],
  "NOUVELLE-ZELANDE": ["NZ"],
  "SINGAPORE": ["SP", "SG"],
  "SINGAPOUR": ["SP", "SG"],
  "INDONESIA": ["IJ", "ID"],
  "INDONESIE": ["IJ", "ID"],
  "MALAYSIA": ["MK", "MY"],
  "MALAISIE": ["MK", "MY"],
  "THAILAND": ["TB", "TH"],
  "THAILANDE": ["TB", "TH"],
  "PHILIPPINES": ["PM", "PH"],
  "VIETNAM": ["VN"],
  "PAKISTAN": ["PK"],
  "BANGLADESH": ["BD"],
  "SRI LANKA": ["LK"],
  "MYANMAR": ["MM"],
  "CAMBODIA": ["KH"],
  "CAMBODGE": ["KH"],
  "MONGOLIA": ["MN"],
  "MONGOLIE": ["MN"],

  // ─── Middle East ───
  "SAUDI ARABIA": ["AB", "SA"],
  "ARABIE SAOUDITE": ["AB", "SA"],
  "UAE": ["UH", "AE"],
  "EMIRATS ARABES UNIS": ["UH", "AE"],
  "QATAR": ["QD", "QA"],
  "KUWAIT": ["KK", "KW"],
  "KOWEIT": ["KK", "KW"],
  "ISRAEL": ["IT", "IL"],
  "BAHRAIN": ["BH"],
  "BAHREIN": ["BH"],
  "OMAN": ["OM"],
  "JORDAN": ["JO"],
  "JORDANIE": ["JO"],
  "LEBANON": ["LB"],
  "LIBAN": ["LB"],
  "IRAQ": ["IQ"],
  "IRAK": ["IQ"],
  "IRAN": ["IR"],

  // ─── Africa ───
  "SOUTH AFRICA": ["SJ", "ZA", "AJ", "XA", "XH"],
  "AFRIQUE DU SUD": ["SJ", "ZA", "AJ", "XA", "XH"],
  "MAURITIUS": ["MP", "MU"],
  "MAURICE": ["MP", "MU"],
  "ILE MAURICE": ["MP", "MU"],
  "NIGERIA": ["NL", "NG"],
  "EGYPT": ["EY", "EG"],
  "EGYPTE": ["EY", "EG"],
  "KENYA": ["KN", "KE"],
  "MOROCCO": ["MC", "MA"],
  "MAROC": ["MC", "MA"],
  "TUNISIA": ["TU", "TN"],
  "TUNISIE": ["TU", "TN"],
  "COTE D'IVOIRE": ["CI"],
  "IVORY COAST": ["CI"],
  "SENEGAL": ["SN"],
  "GHANA": ["GH", "GN"],
  "CONGO": ["CG", "CD"],
  "CAMEROON": ["CM"],
  "CAMEROUN": ["CM"],
  "ALGERIA": ["DZ"],
  "ALGERIE": ["DZ"],
  "ETHIOPIA": ["ET"],
  "ETHIOPIE": ["ET"],
  "TANZANIA": ["TZ"],
  "TANZANIE": ["TZ"],
  "UGANDA": ["UG"],
  "OUGANDA": ["UG"],
  "MOZAMBIQUE": ["MZ"],
  "ZAMBIA": ["ZM"],
  "ZAMBIE": ["ZM"],
  "ZIMBABWE": ["ZW"],
  "BOTSWANA": ["BW"],
  "NAMIBIA": ["NA"],
  "NAMIBIE": ["NA"],
  "RWANDA": ["RW"],
  "MADAGASCAR": ["MG"],
  "MALI": ["ML"],
  "BURKINA FASO": ["BF"],
  "NIGER": ["NE"],
  "BENIN": ["BJ"],
  "TOGO": ["TG"],
  "GABON": ["GA"],
  "MAURITANIA": ["MR"],
  "MAURITANIE": ["MR"],
  "GUINEA": ["GN"],
  "GUINEE": ["GN"],
  "GUINEA EQUATORIAL": ["GQ"],
  "GUINEE EQUATORIALE": ["GQ"],
  "SIERRA LEONE": ["SL"],
  "LIBERIA": ["LR"],
  "ERITREA": ["ER"],
  "ERYTHREE": ["ER"],
  "DJIBOUTI": ["DJ"],
  "SOMALIA": ["SO"],
  "SOMALIE": ["SO"],
  "CHAD": ["TD"],
  "TCHAD": ["TD"],
  "CENTRAL AFRICAN REPUBLIC": ["CF"],
  "REPUBLIQUE CENTRAFRICAINE": ["CF"],
  "SOUTH SUDAN": ["SS"],
  "SOUDAN DU SUD": ["SS"],
  "SUDAN": ["SD"],
  "SOUDAN": ["SD"],
  "LIBYA": ["LY"],
  "LIBYE": ["LY"],
  "ANGOLA": ["AO"],
  "MALAWI": ["MW"],
  "LESOTHO": ["LS"],
  "ESWATINI": ["SZ"],
  "SWAZILAND": ["SZ"],
  "COMOROS": ["KM"],
  "COMORES": ["KM"],
  "SEYCHELLES": ["SC"],
  "CAPE VERDE": ["CV"],
  "CAP-VERT": ["CV"],
  "SAO TOME AND PRINCIPE": ["ST"],
  "SAO TOME ET PRINCIPE": ["ST"],
  "REUNION": ["RE"],
  "MAYOTTE": ["YT"],

  // ─── Regional Groups ───
  "AFRIQUE": ["ZA", "NG", "EG", "KE", "MA", "TN", "GH", "CI", "SN", "CM", "MU", "ET", "TZ", "UG", "DZ", "MZ", "ZM", "ZW", "BW", "NA", "RW", "MG", "AO", "CD", "CG"],
  "AFRICAN EMERGING": ["ZA", "NG", "EG", "KE", "MA", "GH", "CI", "MU", "TN", "ET", "TZ", "SN"],
  "PAYS EMERGENTS AFRICAINS": ["ZA", "NG", "EG", "KE", "MA", "GH", "CI", "MU", "TN", "ET", "TZ", "SN"],
  "AFRIQUE EMERGENTE": ["ZA", "NG", "EG", "KE", "MA", "GH", "CI", "MU", "TN", "ET", "TZ", "SN"],
  "EMERGING AFRICA": ["ZA", "NG", "EG", "KE", "MA", "GH", "CI", "MU", "TN", "ET", "TZ", "SN"],
  "DEVELOPING COUNTRIES": ["NG", "KE", "GH", "CI", "SN", "TZ", "UG", "ET", "MZ", "ZM", "RW", "CM", "MG", "BD", "PK", "VN", "KH", "MM", "MN"],
  "PAYS EN DEVELOPPEMENT": ["NG", "KE", "GH", "CI", "SN", "TZ", "UG", "ET", "MZ", "ZM", "RW", "CM", "MG", "BD", "PK", "VN", "KH", "MM", "MN"],
  "PAYS EN VOIE DE DEVELOPPEMENT": ["NG", "KE", "GH", "CI", "SN", "TZ", "UG", "ET", "MZ", "ZM", "RW", "CM", "MG", "BD", "PK", "VN", "KH", "MM", "MN"],
  "EMERGING MARKETS": ["ZA", "BR", "IN", "CN", "MX", "TR", "ID", "TH", "MY", "PH", "PL", "CZ", "HU", "CL", "CO", "PE", "NG", "EG", "KE", "SA", "AE", "QA"],
  "MARCHES EMERGENTS": ["ZA", "BR", "IN", "CN", "MX", "TR", "ID", "TH", "MY", "PH", "PL", "CZ", "HU", "CL", "CO", "PE", "NG", "EG", "KE", "SA", "AE", "QA"],
  "FRONTIER MARKETS": ["NG", "KE", "MU", "GH", "CI", "SN", "TN", "MA", "VN", "BD", "PK", "LK", "KW", "BH", "JO", "OM"],
  "MARCHES FRONTIERES": ["NG", "KE", "MU", "GH", "CI", "SN", "TN", "MA", "VN", "BD", "PK", "LK", "KW", "BH", "JO", "OM"],
  "BRICS": ["BR", "RU", "IN", "CN", "ZA"],
  "WAEMU": ["CI", "SN", "ML", "BF", "NE", "BJ", "TG", "GN"],
  "UEMOA": ["CI", "SN", "ML", "BF", "NE", "BJ", "TG", "GN"],
  "CEMAC": ["CM", "GA", "CG", "TD", "CF", "GQ"],
  "EAST AFRICA": ["KE", "TZ", "UG", "RW", "ET", "DJ", "SO"],
  "AFRIQUE DE L'EST": ["KE", "TZ", "UG", "RW", "ET", "DJ", "SO"],
  "WEST AFRICA": ["NG", "GH", "CI", "SN", "ML", "BF", "NE", "BJ", "TG", "SL", "LR", "GN"],
  "AFRIQUE DE L'OUEST": ["NG", "GH", "CI", "SN", "ML", "BF", "NE", "BJ", "TG", "SL", "LR", "GN"],
  "NORTH AFRICA": ["MA", "DZ", "TN", "LY", "EG"],
  "AFRIQUE DU NORD": ["MA", "DZ", "TN", "LY", "EG"],
  "SOUTHERN AFRICA": ["ZA", "BW", "NA", "ZM", "ZW", "MZ", "MW", "LS", "SZ"],
  "AFRIQUE AUSTRALE": ["ZA", "BW", "NA", "ZM", "ZW", "MZ", "MW", "LS", "SZ"],
  "CENTRAL AFRICA": ["CM", "CG", "CD", "GA", "CF", "TD", "GQ"],
  "AFRIQUE CENTRALE": ["CM", "CG", "CD", "GA", "CF", "TD", "GQ"],
  "INDIAN OCEAN": ["MU", "MG", "SC", "KM", "RE", "YT"],
  "OCEAN INDIEN": ["MU", "MG", "SC", "KM", "RE", "YT"],
};

export function getCountryCodes(query: string): string[] {
  const q = query.trim().toUpperCase();
  
  // Direct match
  if (COUNTRY_MAP[q]) return COUNTRY_MAP[q];
  
  // Partial match
  const matches: string[] = [];
  for (const [name, codes] of Object.entries(COUNTRY_MAP)) {
    if (name.includes(q) || q.includes(name)) {
      matches.push(...codes);
    }
  }
  
  // If input is already a 2-letter code, include it
  if (q.length === 2) matches.push(q);
  
  return [...new Set(matches)];
}
