export interface CountryEntry {
  label: string;
  query: string;
}

export interface ZoneGroup {
  zone: string;
  emoji: string;
  countries: CountryEntry[];
}

export const COUNTRY_ZONES: ZoneGroup[] = [
  {
    zone: "Afrique",
    emoji: "🌍",
    countries: [
      { label: "Afrique du Sud", query: "SOUTH AFRICA" },
      { label: "Algérie", query: "ALGERIA" },
      { label: "Angola", query: "ANGOLA" },
      { label: "Bénin", query: "BENIN" },
      { label: "Botswana", query: "BOTSWANA" },
      { label: "Burkina Faso", query: "BURKINA FASO" },
      { label: "Cameroun", query: "CAMEROON" },
      { label: "Cap-Vert", query: "CAPE VERDE" },
      { label: "Comores", query: "COMOROS" },
      { label: "Congo", query: "CONGO" },
      { label: "Côte d'Ivoire", query: "COTE D'IVOIRE" },
      { label: "Djibouti", query: "DJIBOUTI" },
      { label: "Égypte", query: "EGYPT" },
      { label: "Érythrée", query: "ERITREA" },
      { label: "Eswatini", query: "ESWATINI" },
      { label: "Éthiopie", query: "ETHIOPIA" },
      { label: "Gabon", query: "GABON" },
      { label: "Ghana", query: "GHANA" },
      { label: "Guinée", query: "GUINEA" },
      { label: "Guinée Équatoriale", query: "GUINEA EQUATORIAL" },
      { label: "Kenya", query: "KENYA" },
      { label: "Lesotho", query: "LESOTHO" },
      { label: "Libéria", query: "LIBERIA" },
      { label: "Libye", query: "LIBYA" },
      { label: "Madagascar", query: "MADAGASCAR" },
      { label: "Malawi", query: "MALAWI" },
      { label: "Mali", query: "MALI" },
      { label: "Maroc", query: "MOROCCO" },
      { label: "Maurice", query: "MAURITIUS" },
      { label: "Mauritanie", query: "MAURITANIA" },
      { label: "Mozambique", query: "MOZAMBIQUE" },
      { label: "Namibie", query: "NAMIBIA" },
      { label: "Niger", query: "NIGER" },
      { label: "Nigeria", query: "NIGERIA" },
      { label: "Ouganda", query: "UGANDA" },
      { label: "RCA", query: "CENTRAL AFRICAN REPUBLIC" },
      { label: "Rwanda", query: "RWANDA" },
      { label: "Sénégal", query: "SENEGAL" },
      { label: "Seychelles", query: "SEYCHELLES" },
      { label: "Sierra Leone", query: "SIERRA LEONE" },
      { label: "Somalie", query: "SOMALIA" },
      { label: "Soudan", query: "SUDAN" },
      { label: "Soudan du Sud", query: "SOUTH SUDAN" },
      { label: "Tanzanie", query: "TANZANIA" },
      { label: "Tchad", query: "CHAD" },
      { label: "Togo", query: "TOGO" },
      { label: "Tunisie", query: "TUNISIA" },
      { label: "Zambie", query: "ZAMBIA" },
      { label: "Zimbabwe", query: "ZIMBABWE" },
      // Groupes régionaux africains
      { label: "── Groupes ──", query: "" },
      { label: "🔥 Afrique Émergente", query: "AFRICAN EMERGING" },
      { label: "🌱 Pays en Développement", query: "DEVELOPING COUNTRIES" },
      { label: "🏦 UEMOA / WAEMU", query: "UEMOA" },
      { label: "🏦 CEMAC", query: "CEMAC" },
      { label: "🧭 Afrique de l'Est", query: "EAST AFRICA" },
      { label: "🧭 Afrique de l'Ouest", query: "WEST AFRICA" },
      { label: "🧭 Afrique du Nord", query: "NORTH AFRICA" },
      { label: "🧭 Afrique Australe", query: "SOUTHERN AFRICA" },
      { label: "🧭 Afrique Centrale", query: "CENTRAL AFRICA" },
      { label: "🌊 Océan Indien", query: "INDIAN OCEAN" },
    ],
  },
  {
    zone: "Amérique du Nord",
    emoji: "🇺🇸",
    countries: [
      { label: "Canada", query: "CANADA" },
      { label: "États-Unis", query: "USA" },
      { label: "Mexique", query: "MEXICO" },
    ],
  },
  {
    zone: "Amérique Latine",
    emoji: "🌎",
    countries: [
      { label: "Argentine", query: "ARGENTINA" },
      { label: "Brésil", query: "BRAZIL" },
      { label: "Chili", query: "CHILE" },
      { label: "Colombie", query: "COLOMBIA" },
      { label: "Costa Rica", query: "COSTA RICA" },
      { label: "Équateur", query: "ECUADOR" },
      { label: "Jamaïque", query: "JAMAICA" },
      { label: "Panama", query: "PANAMA" },
      { label: "Pérou", query: "PERU" },
      { label: "Trinité-et-Tobago", query: "TRINIDAD AND TOBAGO" },
      { label: "Uruguay", query: "URUGUAY" },
      { label: "Venezuela", query: "VENEZUELA" },
    ],
  },
  {
    zone: "Asie",
    emoji: "🌏",
    countries: [
      { label: "Bangladesh", query: "BANGLADESH" },
      { label: "Cambodge", query: "CAMBODIA" },
      { label: "Chine", query: "CHINA" },
      { label: "Corée du Sud", query: "SOUTH KOREA" },
      { label: "Hong Kong", query: "HONG KONG" },
      { label: "Inde", query: "INDIA" },
      { label: "Indonésie", query: "INDONESIA" },
      { label: "Japon", query: "JAPAN" },
      { label: "Malaisie", query: "MALAYSIA" },
      { label: "Mongolie", query: "MONGOLIA" },
      { label: "Myanmar", query: "MYANMAR" },
      { label: "Pakistan", query: "PAKISTAN" },
      { label: "Philippines", query: "PHILIPPINES" },
      { label: "Singapour", query: "SINGAPORE" },
      { label: "Sri Lanka", query: "SRI LANKA" },
      { label: "Taïwan", query: "TAIWAN" },
      { label: "Thaïlande", query: "THAILAND" },
      { label: "Vietnam", query: "VIETNAM" },
      // Groupes
      { label: "── Groupes ──", query: "" },
      { label: "🔥 Marchés Émergents", query: "EMERGING MARKETS" },
      { label: "🔥 Marchés Frontières", query: "FRONTIER MARKETS" },
      { label: "🏦 BRICS", query: "BRICS" },
    ],
  },
  {
    zone: "Europe",
    emoji: "🇪🇺",
    countries: [
      { label: "Allemagne", query: "GERMANY" },
      { label: "Autriche", query: "AUSTRIA" },
      { label: "Belgique", query: "BELGIUM" },
      { label: "Bulgarie", query: "BULGARIA" },
      { label: "Chypre", query: "CYPRUS" },
      { label: "Croatie", query: "CROATIA" },
      { label: "Danemark", query: "DENMARK" },
      { label: "Espagne", query: "SPAIN" },
      { label: "Estonie", query: "ESTONIA" },
      { label: "Finlande", query: "FINLAND" },
      { label: "France", query: "FRANCE" },
      { label: "Grèce", query: "GREECE" },
      { label: "Hongrie", query: "HUNGARY" },
      { label: "Irlande", query: "IRELAND" },
      { label: "Islande", query: "ICELAND" },
      { label: "Italie", query: "ITALY" },
      { label: "Lettonie", query: "LATVIA" },
      { label: "Lituanie", query: "LITHUANIA" },
      { label: "Luxembourg", query: "LUXEMBOURG" },
      { label: "Malte", query: "MALTA" },
      { label: "Norvège", query: "NORWAY" },
      { label: "Pays-Bas", query: "NETHERLANDS" },
      { label: "Pologne", query: "POLAND" },
      { label: "Portugal", query: "PORTUGAL" },
      { label: "Rép. Tchèque", query: "CZECH REPUBLIC" },
      { label: "Roumanie", query: "ROMANIA" },
      { label: "Royaume-Uni", query: "UK" },
      { label: "Russie", query: "RUSSIA" },
      { label: "Serbie", query: "SERBIA" },
      { label: "Slovaquie", query: "SLOVAKIA" },
      { label: "Slovénie", query: "SLOVENIA" },
      { label: "Suède", query: "SWEDEN" },
      { label: "Suisse", query: "SWITZERLAND" },
      { label: "Turquie", query: "TURKEY" },
      { label: "Ukraine", query: "UKRAINE" },
    ],
  },
  {
    zone: "Moyen-Orient",
    emoji: "🕌",
    countries: [
      { label: "Arabie Saoudite", query: "SAUDI ARABIA" },
      { label: "Bahreïn", query: "BAHRAIN" },
      { label: "EAU", query: "UAE" },
      { label: "Irak", query: "IRAQ" },
      { label: "Iran", query: "IRAN" },
      { label: "Israël", query: "ISRAEL" },
      { label: "Jordanie", query: "JORDAN" },
      { label: "Koweït", query: "KUWAIT" },
      { label: "Liban", query: "LEBANON" },
      { label: "Oman", query: "OMAN" },
      { label: "Qatar", query: "QATAR" },
    ],
  },
  {
    zone: "Océanie",
    emoji: "🏝️",
    countries: [
      { label: "Australie", query: "AUSTRALIA" },
      { label: "Nouvelle-Zélande", query: "NEW ZEALAND" },
    ],
  },
];
