import * as XLSX from "xlsx";

export function generateProjectDocument() {
  const wb = XLSX.utils.book_new();

  // ─── 1. VUE D'ENSEMBLE ───
  const overview = [
    ["CAHIER DE PROJET — DATA ENRICHER FINANCIER"],
    [""],
    ["Rubrique", "Détail"],
    ["Nom du projet", "Data Enricher Financier"],
    ["Version", "v4.3 (ENRICHER_v4.3)"],
    ["Date de création", "Mars 2026"],
    ["Type", "Application web SaaS (Single Page Application)"],
    ["Objectif principal", "Transformer un identifiant financier (ISIN, Ticker, CUSIP, SEDOL, FIGI) en un ensemble complet de données enrichies (RIC, MIC, secteur, devise, pays, etc.)"],
    ["Public cible", "Analystes financiers, gestionnaires de portefeuilles, data managers, compliance officers"],
    ["Stack technique", "React 18 + TypeScript + Vite + Tailwind CSS + Lovable Cloud (Supabase)"],
    ["API externe", "OpenFIGI v3 (Bloomberg Open Symbology)"],
    ["Authentification", "Email/mot de passe avec vérification email"],
    ["Base de données", "PostgreSQL (via Lovable Cloud)"],
    ["Temps réel", "Oui — Supabase Realtime (WebSockets)"],
    ["Export", "XLSX (Excel) via bibliothèque xlsx"],
    ["Déploiement", "Lovable Cloud (frontend + backend serverless)"],
    [""],
    ["RÉSUMÉ FONCTIONNEL"],
    ["", "Ce logiciel permet d'enrichir automatiquement des données financières à partir d'identifiants standards de l'industrie."],
    ["", "Il interroge l'API OpenFIGI de Bloomberg pour récupérer les métadonnées complètes d'un actif financier."],
    ["", "Les données sont stockées en base, synchronisées en temps réel, et peuvent être exportées en Excel."],
    ["", "Le système supporte l'import unitaire, par lot (bulk), et par pays (toutes les bourses d'un territoire)."],
  ];
  const wsOverview = XLSX.utils.aoa_to_sheet(overview);
  wsOverview["!cols"] = [{ wch: 30 }, { wch: 100 }];
  XLSX.utils.book_append_sheet(wb, wsOverview, "1. Vue d'ensemble");

  // ─── 2. FONCTIONNALITÉS ───
  const features = [
    ["CATALOGUE DES FONCTIONNALITÉS"],
    [""],
    ["Module", "Fonctionnalité", "Description", "Statut"],
    ["Recherche", "Recherche unitaire", "Saisir un ISIN, ticker ou identifiant pour enrichir un actif", "✅ Actif"],
    ["Recherche", "Détection automatique du type", "Le système détecte si l'entrée est un ISIN, CUSIP, SEDOL, FIGI ou Ticker", "✅ Actif"],
    ["Recherche", "Recherche temps réel EODHD", "Interroge l'API EODHD en temps réel pour chaque recherche", "✅ Actif"],
    ["Recherche", "Fallback base de données", "Si l'API est indisponible, cherche dans la base de données utilisateur", "✅ Actif"],
    ["Import", "Import bulk (par lot)", "Coller une liste d'identifiants séparés par des virgules/retours ligne", "✅ Actif"],
    ["Import", "Import par pays", "Sélectionner un pays pour importer tous les actifs de ses bourses", "✅ Actif"],
    ["Import", "Import multi-exchange", "Interroge toutes les bourses d'un pays simultanément (ex: FP + PA pour France)", "✅ Actif"],
    ["Import", "Pagination profonde", "Parcourt automatiquement toutes les pages de résultats (jusqu'à 5000 actifs)", "✅ Actif"],
    ["Data Manager", "Vue tableur Excel-like", "Tableau interactif avec pagination, tri et filtres", "✅ Actif"],
    ["Data Manager", "Édition inline", "Double-cliquer sur une cellule pour la modifier directement", "✅ Actif"],
    ["Data Manager", "Filtre par secteur", "Menu déroulant avec 40+ secteurs financiers", "✅ Actif"],
    ["Data Manager", "Filtre par pays", "Recherche textuelle par nom de pays", "✅ Actif"],
    ["Data Manager", "Filtre favoris", "Afficher uniquement les actifs marqués comme favoris", "✅ Actif"],
    ["Data Manager", "Suppression groupée", "Sélectionner et supprimer plusieurs actifs simultanément", "✅ Actif"],
    ["Data Manager", "Indicateur LIVE", "Badge vert pulsant indiquant la connexion temps réel active", "✅ Actif"],
    ["Data Manager", "Export XLSX", "Télécharger les données filtrées au format Excel", "✅ Actif"],
    ["Favoris", "Marquer/démarquer", "Cliquer sur l'étoile pour ajouter/retirer un actif des favoris", "✅ Actif"],
    ["Favoris", "Synchronisation", "Les favoris sont liés au compte utilisateur et persistent entre sessions", "✅ Actif"],
    ["Comparaison", "Comparaison côte à côte", "Comparer jusqu'à 4 actifs simultanément", "✅ Actif"],
    ["Comparaison", "Graphique radar", "Visualisation de la couverture des données par actif", "✅ Actif"],
    ["Comparaison", "Graphique barres", "Comparaison de la complétude des champs enrichis", "✅ Actif"],
    ["Notifications", "Alertes temps réel", "Toast notifications quand un autre utilisateur importe des actifs", "✅ Actif"],
    ["Auth", "Inscription/Connexion", "Formulaire email + mot de passe avec vérification", "✅ Actif"],
    ["Auth", "Réinitialisation mdp", "Flux de réinitialisation par email", "✅ Actif"],
    ["Auth", "Profil utilisateur", "Page de gestion du profil (nom, entreprise, avatar, thème)", "✅ Actif"],
    ["Auth", "Demande d'accès", "Formulaire public pour demander un accès au logiciel", "✅ Actif"],
    ["UI", "Mode sombre/clair", "Basculer entre thème clair et sombre", "✅ Actif"],
    ["UI", "Responsive design", "Adapté desktop et tablette", "✅ Actif"],
    ["UI", "Historique recherches", "Sauvegarde locale des dernières recherches effectuées", "✅ Actif"],
  ];
  const wsFeatures = XLSX.utils.aoa_to_sheet(features);
  wsFeatures["!cols"] = [{ wch: 18 }, { wch: 28 }, { wch: 75 }, { wch: 10 }];
  XLSX.utils.book_append_sheet(wb, wsFeatures, "2. Fonctionnalités");

  // ─── 3. ARCHITECTURE TECHNIQUE ───
  const arch = [
    ["ARCHITECTURE TECHNIQUE"],
    [""],
    ["Couche", "Technologie", "Rôle", "Version"],
    ["Frontend", "React", "Bibliothèque UI composants réactifs", "18.3"],
    ["Frontend", "TypeScript", "Typage statique pour fiabilité du code", "5.8"],
    ["Frontend", "Vite", "Bundler/serveur de développement ultra-rapide", "8.0"],
    ["Frontend", "Tailwind CSS", "Framework CSS utilitaire", "3.4"],
    ["Frontend", "shadcn/ui", "Composants UI accessibles (Radix UI)", "latest"],
    ["Frontend", "React Router", "Navigation SPA (Single Page Application)", "6.30"],
    ["Frontend", "TanStack Query", "Gestion d'état serveur et cache", "5.83"],
    ["Frontend", "Recharts", "Bibliothèque de graphiques (radar, barres)", "2.15"],
    ["Frontend", "Framer Motion", "Animations et transitions", "12.37"],
    ["Frontend", "xlsx", "Génération de fichiers Excel (.xlsx)", "0.18"],
    ["Frontend", "Sonner", "Système de toast notifications", "1.7"],
    ["Backend", "Lovable Cloud", "Base de données PostgreSQL + Auth + Realtime + Edge Functions", "-"],
    ["Backend", "Edge Functions", "Fonctions serverless Deno (proxy API OpenFIGI)", "Deno"],
    ["Backend", "Supabase Realtime", "WebSockets pour sync temps réel", "-"],
    ["API externe", "OpenFIGI v3", "API Bloomberg Open Symbology pour enrichissement", "v3"],
    [""],
    ["STRUCTURE DES FICHIERS PRINCIPAUX"],
    [""],
    ["Fichier", "Rôle"],
    ["src/App.tsx", "Point d'entrée, routage et providers globaux"],
    ["src/pages/Index.tsx", "Page principale : recherche, import bulk, import pays"],
    ["src/pages/DataManager.tsx", "Gestionnaire de données type Excel avec temps réel"],
    ["src/pages/Compare.tsx", "Comparateur d'actifs côte à côte avec graphiques"],
    ["src/pages/Dashboard.tsx", "Tableau de bord (à enrichir)"],
    ["src/pages/Auth.tsx", "Page de connexion / inscription"],
    ["src/pages/Profile.tsx", "Gestion du profil utilisateur"],
    ["src/pages/ResetPassword.tsx", "Réinitialisation du mot de passe"],
    ["src/lib/asset-service.ts", "Service central : recherche EODHD → DB fallback → CoinGecko"],
    ["src/lib/mock-data.ts", "Types TypeScript pour les actifs financiers"],
    ["src/lib/country-codes.ts", "Mapping pays → codes boursiers (exchCodes)"],
    ["src/hooks/use-auth.tsx", "Hook d'authentification (session, user)"],
    ["src/hooks/use-favorites.ts", "Hook de gestion des favoris"],
    ["src/hooks/use-asset-notifications.ts", "Hook de notifications temps réel"],
    ["src/hooks/use-search-history.ts", "Hook d'historique des recherches"],
    ["src/components/AssetTable.tsx", "Composant tableau d'affichage des résultats"],
    ["src/components/BulkImport.tsx", "Composant d'import par lot"],
    ["src/components/CountrySearch.tsx", "Composant d'import par pays"],
    ["src/components/DataGrid.tsx", "Grille de données interactive"],
    ["supabase/functions/eodhd-lookup/index.ts", "Edge Function proxy vers l'API EODHD"],
  ];
  const wsArch = XLSX.utils.aoa_to_sheet(arch);
  wsArch["!cols"] = [{ wch: 45 }, { wch: 30 }, { wch: 60 }, { wch: 10 }];
  XLSX.utils.book_append_sheet(wb, wsArch, "3. Architecture");

  // ─── 4. SCHÉMA BASE DE DONNÉES ───
  const db = [
    ["SCHÉMA DE LA BASE DE DONNÉES"],
    [""],
    ["TABLE: financial_assets — Actifs financiers enrichis"],
    ["Colonne", "Type", "Nullable", "Défaut", "Description"],
    ["id", "uuid", "Non", "gen_random_uuid()", "Identifiant unique de l'actif"],
    ["asset_name", "text", "Non", "-", "Nom de l'actif (ex: APPLE INC)"],
    ["isin", "text", "Non", "-", "Code ISIN unique (ex: US0378331005)"],
    ["sector", "text", "Oui", "-", "Secteur d'activité (Finance, Tech, etc.)"],
    ["acf", "text", "Oui", "-", "Composite FIGI (identifiant Bloomberg)"],
    ["ric", "text", "Oui", "-", "Reuters Instrument Code"],
    ["ticker", "text", "Oui", "-", "Symbole boursier court (ex: AAPL)"],
    ["symbol", "text", "Oui", "-", "Symbole alternatif"],
    ["country_id", "text", "Oui", "-", "Code ISO pays (ex: US, FR, GB)"],
    ["country", "text", "Oui", "-", "Nom complet du pays"],
    ["mic_code", "text", "Oui", "-", "Market Identifier Code (ex: XPAR, XNYS)"],
    ["currency_id", "text", "Oui", "-", "Code devise ISO (ex: EUR, USD)"],
    ["currency", "text", "Oui", "-", "Devise de cotation"],
    ["description", "text", "Oui", "-", "Description générée (nom | type | secteur | bourse)"],
    ["source", "text", "Oui", "manual", "Origine des données (openfigi, local_dataset, manual)"],
    ["user_id", "uuid", "Oui", "-", "ID de l'utilisateur propriétaire"],
    ["created_at", "timestamptz", "Non", "now()", "Date de création"],
    ["updated_at", "timestamptz", "Non", "now()", "Date de dernière modification"],
    [""],
    ["TABLE: favorites — Favoris utilisateur"],
    ["Colonne", "Type", "Nullable", "Défaut", "Description"],
    ["id", "uuid", "Non", "gen_random_uuid()", "Identifiant unique"],
    ["user_id", "uuid", "Non", "-", "ID de l'utilisateur"],
    ["asset_id", "uuid", "Non", "-", "ID de l'actif marqué"],
    ["created_at", "timestamptz", "Non", "now()", "Date d'ajout aux favoris"],
    [""],
    ["TABLE: profiles — Profils utilisateurs"],
    ["Colonne", "Type", "Nullable", "Défaut", "Description"],
    ["id", "uuid", "Non", "gen_random_uuid()", "Identifiant unique"],
    ["user_id", "uuid", "Non", "-", "ID de l'utilisateur (auth)"],
    ["display_name", "text", "Oui", "-", "Nom d'affichage"],
    ["company", "text", "Oui", "-", "Entreprise"],
    ["avatar_url", "text", "Oui", "-", "URL de l'avatar"],
    ["preferred_theme", "text", "Oui", "light", "Thème préféré (light/dark)"],
    ["created_at", "timestamptz", "Non", "now()", "Date de création"],
    ["updated_at", "timestamptz", "Non", "now()", "Date de modification"],
    [""],
    ["TABLE: access_requests — Demandes d'accès"],
    ["Colonne", "Type", "Nullable", "Défaut", "Description"],
    ["id", "uuid", "Non", "gen_random_uuid()", "Identifiant unique"],
    ["full_name", "text", "Non", "-", "Nom complet du demandeur"],
    ["email", "text", "Non", "-", "Email du demandeur"],
    ["company", "text", "Oui", "-", "Entreprise"],
    ["message", "text", "Oui", "-", "Message de motivation"],
    ["status", "text", "Non", "pending", "Statut (pending, approved, rejected)"],
    ["created_at", "timestamptz", "Non", "now()", "Date de la demande"],
    ["updated_at", "timestamptz", "Non", "now()", "Date de modification"],
  ];
  const wsDb = XLSX.utils.aoa_to_sheet(db);
  wsDb["!cols"] = [{ wch: 20 }, { wch: 18 }, { wch: 10 }, { wch: 20 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, wsDb, "4. Base de données");

  // ─── 5. SÉCURITÉ (RLS) ───
  const security = [
    ["POLITIQUES DE SÉCURITÉ (Row-Level Security)"],
    [""],
    ["Table", "Action", "Règle", "Description"],
    ["financial_assets", "SELECT", "user_id = auth.uid() OR user_id IS NULL", "Lecture : ses propres actifs + actifs publics"],
    ["financial_assets", "INSERT", "user_id = auth.uid()", "Insertion : uniquement sous son propre ID"],
    ["financial_assets", "UPDATE", "user_id = auth.uid()", "Modification : uniquement ses propres actifs"],
    ["financial_assets", "DELETE", "user_id = auth.uid()", "Suppression : uniquement ses propres actifs"],
    ["favorites", "SELECT", "user_id = auth.uid()", "Lecture : ses propres favoris uniquement"],
    ["favorites", "INSERT", "user_id = auth.uid()", "Ajout : sous son propre ID uniquement"],
    ["favorites", "DELETE", "user_id = auth.uid()", "Suppression : ses propres favoris uniquement"],
    ["profiles", "SELECT", "user_id = auth.uid()", "Lecture : son propre profil"],
    ["profiles", "INSERT", "user_id = auth.uid()", "Création : son propre profil"],
    ["profiles", "UPDATE", "user_id = auth.uid()", "Modification : son propre profil"],
    ["access_requests", "INSERT", "Validation email + longueurs", "Tout le monde peut soumettre (avec validation)"],
    [""],
    ["PRINCIPES DE SÉCURITÉ"],
    ["", "Toutes les tables ont RLS activé"],
    ["", "Aucune donnée n'est accessible sans authentification (sauf access_requests INSERT)"],
    ["", "Les Edge Functions valident les entrées côté serveur"],
    ["", "Les clés API (OpenFIGI) sont stockées en secrets sécurisés"],
    ["", "Pas de requêtes SQL brutes — uniquement le SDK typé"],
  ];
  const wsSec = XLSX.utils.aoa_to_sheet(security);
  wsSec["!cols"] = [{ wch: 22 }, { wch: 12 }, { wch: 45 }, { wch: 55 }];
  XLSX.utils.book_append_sheet(wb, wsSec, "5. Sécurité RLS");

  // ─── 6. FLUX DE DONNÉES ───
  const flows = [
    ["FLUX DE DONNÉES"],
    [""],
    ["FLUX 1 : Recherche unitaire d'un actif"],
    ["Étape", "Action", "Détail"],
    ["1", "Saisie utilisateur", "L'utilisateur entre un identifiant (ISIN, Ticker, nom, etc.)"],
    ["2", "Appel EODHD temps réel", "Recherche en direct sur l'API EODHD (source primaire)"],
    ["3", "Fallback DB locale", "Si EODHD indisponible, cherche dans la base de données utilisateur"],
    ["4", "Fallback CoinGecko", "Pour les crypto-monnaies si EODHD ne retourne rien"],
    ["5", "Sauvegarde optionnelle", "L'utilisateur peut enregistrer les résultats dans sa base de données"],
    ["6", "Affichage", "Les résultats sont affichés avec tous les champs enrichis"],
    [""],
    ["FLUX 2 : Import par pays"],
    ["Étape", "Action", "Détail"],
    ["1", "Sélection pays", "L'utilisateur choisit un pays (ex: France)"],
    ["2", "Résolution bourses", "Le système identifie tous les codes boursiers du pays (France → FP, PA)"],
    ["3", "Requêtes parallèles", "L'Edge Function interroge chaque bourse avec pagination profonde"],
    ["4", "Dédoublonnage", "Les doublons sont éliminés par FIGI/compositeFIGI"],
    ["5", "MIC fallback", "Si OpenFIGI ne renvoie pas le MIC code, il est déduit du code bourse"],
    ["6", "Persistance bulk", "Tous les actifs sont insérés en base (upsert)"],
    ["7", "Notification live", "Les autres utilisateurs connectés reçoivent une notification toast"],
    [""],
    ["FLUX 3 : Synchronisation temps réel"],
    ["Étape", "Action", "Détail"],
    ["1", "Connexion WebSocket", "Au chargement du Data Manager, un canal Realtime est ouvert"],
    ["2", "Écoute INSERT", "Le canal écoute les événements INSERT sur financial_assets"],
    ["3", "Écoute UPDATE", "Le canal écoute les événements UPDATE sur financial_assets"],
    ["4", "Écoute DELETE", "Le canal écoute les événements DELETE sur financial_assets"],
    ["5", "Mise à jour UI", "Le tableau se met à jour automatiquement sans rechargement"],
    ["6", "Notification", "Si l'auteur est un autre utilisateur, un toast s'affiche"],
  ];
  const wsFlows = XLSX.utils.aoa_to_sheet(flows);
  wsFlows["!cols"] = [{ wch: 10 }, { wch: 28 }, { wch: 80 }];
  XLSX.utils.book_append_sheet(wb, wsFlows, "6. Flux de données");

  // ─── 7. API OpenFIGI ───
  const api = [
    ["API OPENFIGI — DOCUMENTATION DE RÉFÉRENCE"],
    [""],
    ["Propriété", "Valeur"],
    ["URL de base", "https://api.openfigi.com/v3"],
    ["Authentification", "Optionnelle (X-OPENFIGI-APIKEY header)"],
    ["Limite sans clé", "25 requêtes/minute, 10 jobs/requête"],
    ["Limite avec clé", "250 requêtes/minute, 100 jobs/requête"],
    ["Format", "JSON (POST)"],
    [""],
    ["ENDPOINTS UTILISÉS"],
    ["Endpoint", "Méthode", "Usage"],
    ["/v3/mapping", "POST", "Recherche par identifiant exact (ISIN, CUSIP, SEDOL, FIGI, Ticker)"],
    ["/v3/search", "POST", "Recherche textuelle libre ou par code bourse (exchCode)"],
    [""],
    ["CHAMPS RETOURNÉS PAR OPENFIGI"],
    ["Champ API", "Champ local", "Description"],
    ["figi", "acf (si composite absent)", "Financial Instrument Global Identifier"],
    ["compositeFIGI", "acf", "Composite FIGI (niveau instrument)"],
    ["name", "asset_name", "Nom officiel de l'instrument"],
    ["ticker", "ticker / symbol", "Symbole boursier"],
    ["exchCode", "→ country, country_id", "Code bourse Bloomberg (ex: FP, UN, LN)"],
    ["micCode", "mic_code", "Market Identifier Code ISO 10383"],
    ["securityCurrency", "currency / currency_id", "Devise de cotation"],
    ["marketSector", "sector", "Secteur de marché (Equity, Govt, Corp, etc.)"],
    ["securityType", "description", "Type de titre (Common Stock, ETF, Bond, etc.)"],
    ["securityType2", "sector (fallback)", "Sous-type de titre"],
    [""],
    ["MAPPING EXCHANGE → MIC (FALLBACK)"],
    ["Code Bourse", "MIC Code", "Place boursière"],
    ["UN", "XNYS", "New York Stock Exchange"],
    ["UW", "XNAS", "NASDAQ"],
    ["UQ", "XNAS", "NASDAQ (Global Select)"],
    ["LN", "XLON", "London Stock Exchange"],
    ["FP", "XPAR", "Euronext Paris"],
    ["PA", "XPAR", "Euronext Paris (alt)"],
    ["GR", "XFRA", "Frankfurt Stock Exchange"],
    ["JT", "XTKS", "Tokyo Stock Exchange"],
    ["HK", "XHKG", "Hong Kong Stock Exchange"],
    ["SS", "XSHG", "Shanghai Stock Exchange"],
    ["SZ", "XSHE", "Shenzhen Stock Exchange"],
    ["CT", "XTSE", "Toronto Stock Exchange"],
    ["AT", "XASX", "Australian Securities Exchange"],
    ["IM", "XMIL", "Borsa Italiana (Milan)"],
    ["SM", "XMAD", "Bolsa de Madrid"],
    ["NA", "XAMS", "Euronext Amsterdam"],
    ["BB", "XBRU", "Euronext Brussels"],
    ["VX", "XSWX", "SIX Swiss Exchange"],
    ["SP", "XSES", "Singapore Exchange"],
    ["IB", "XBOM", "Bombay Stock Exchange"],
    ["IN", "XNSE", "National Stock Exchange India"],
    ["SJ", "XJSE", "Johannesburg Stock Exchange"],
    ["BZ", "BVMF", "B3 (Bovespa) São Paulo"],
    ["KS", "XKRX", "Korea Exchange"],
    ["TT", "XTAI", "Taiwan Stock Exchange"],
    ["MM", "XMEX", "Bolsa Mexicana de Valores"],
    ["MP", "XMAU", "Stock Exchange of Mauritius"],
  ];
  const wsApi = XLSX.utils.aoa_to_sheet(api);
  wsApi["!cols"] = [{ wch: 25 }, { wch: 30 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, wsApi, "7. API OpenFIGI");

  // ─── 8. GLOSSAIRE ───
  const glossary = [
    ["GLOSSAIRE — TERMES CLÉS"],
    [""],
    ["Terme", "Abréviation", "Définition complète"],
    ["International Securities Identification Number", "ISIN", "Code unique de 12 caractères identifiant un titre financier à l'échelle mondiale. Format: 2 lettres pays + 9 caractères alphanumériques + 1 chiffre de contrôle. Ex: US0378331005 (Apple Inc.)"],
    ["Financial Instrument Global Identifier", "FIGI", "Identifiant global de 12 caractères créé par Bloomberg pour identifier de manière unique les instruments financiers. Format: BBG + 9 caractères. Ex: BBG000B9XRY4"],
    ["Composite FIGI", "ACF", "Version agrégée du FIGI qui regroupe un même instrument coté sur plusieurs bourses sous un seul identifiant. Aussi appelé 'Aggregate Composite FIGI'."],
    ["Reuters Instrument Code", "RIC", "Code utilisé par Refinitiv (ex-Thomson Reuters) pour identifier un instrument sur une bourse spécifique. Format: TICKER.EXCHCODE. Ex: AAPL.UW"],
    ["Market Identifier Code", "MIC", "Code ISO 10383 de 4 caractères identifiant une place boursière. Ex: XPAR (Euronext Paris), XNYS (NYSE), XNAS (NASDAQ)"],
    ["Committee on Uniform Security Identification Procedures", "CUSIP", "Code de 9 caractères utilisé principalement en Amérique du Nord pour identifier les titres financiers. Ex: 037833100 (Apple)"],
    ["Stock Exchange Daily Official List", "SEDOL", "Code de 7 caractères attribué par la London Stock Exchange pour identifier les titres au Royaume-Uni et en Irlande. Ex: 2046251 (Apple sur LSE)"],
    ["Ticker / Symbol", "Ticker", "Abréviation alphabétique courte représentant un titre coté en bourse. Ex: AAPL (Apple), MSFT (Microsoft), BNP (BNP Paribas)"],
    ["Exchange Code", "exchCode", "Code court Bloomberg identifiant une bourse. Ex: UN = NYSE, UW = NASDAQ, FP = Euronext Paris, LN = London SE"],
    ["Row-Level Security", "RLS", "Mécanisme de sécurité PostgreSQL qui restreint l'accès aux lignes d'une table selon des règles définies (ex: un utilisateur ne voit que SES données)"],
    ["Edge Function", "EF", "Fonction serverless exécutée côté serveur (Deno) qui sert de proxy sécurisé vers des APIs externes. Évite d'exposer les clés API côté client."],
    ["Realtime", "-", "Technologie WebSocket permettant la synchronisation instantanée des données entre le serveur et tous les clients connectés, sans rechargement de page."],
    ["Upsert", "-", "Opération de base de données combinant INSERT et UPDATE : si la ligne existe (conflit sur clé unique), elle est mise à jour ; sinon elle est créée."],
    ["SPA", "SPA", "Single Page Application — Application web qui charge une seule page HTML et met à jour dynamiquement le contenu sans rechargement complet."],
    ["SDK", "SDK", "Software Development Kit — Ensemble d'outils et bibliothèques pour interagir avec un service (ici: le SDK Supabase pour la base de données)."],
    ["Toast", "-", "Notification éphémère qui apparaît brièvement à l'écran pour informer l'utilisateur d'un événement (succès, erreur, info)."],
    ["WebSocket", "WS", "Protocole de communication bidirectionnel persistant entre client et serveur, permettant les mises à jour en temps réel."],
    ["Common Stock", "-", "Action ordinaire — Titre de propriété dans une entreprise cotée donnant droit de vote et dividendes."],
    ["ETF", "ETF", "Exchange-Traded Fund — Fonds indiciel coté en bourse qui réplique la performance d'un indice (ex: S&P 500)."],
    ["ETP", "ETP", "Exchange-Traded Product — Catégorie générale incluant les ETF, ETN et ETC cotés en bourse."],
    ["Market Sector", "-", "Classification du marché dans OpenFIGI: Equity (actions), Govt (obligations d'État), Corp (obligations d'entreprise), Mtge (hypothèques), etc."],
    ["Pagination profonde", "-", "Technique de parcours de grandes quantités de données en effectuant des requêtes successives avec un décalage (offset/start) croissant."],
    ["Dédoublonnage", "-", "Processus d'élimination des doublons lors de l'import massif, basé sur l'unicité du FIGI ou du compositeFIGI."],
    ["Scoring de pertinence", "-", "Algorithme qui classe les résultats OpenFIGI par score : Common Stock (+10), bourse majeure (+5), ticker exact (+8), etc."],
    ["Proxy API", "-", "Serveur intermédiaire (Edge Function) qui relaie les requêtes du client vers une API externe, ajoutant authentification et sécurité."],
    ["ISO 4217", "-", "Norme internationale définissant les codes alphabétiques de 3 lettres pour les devises. Ex: EUR, USD, GBP, JPY."],
    ["ISO 3166-1", "-", "Norme internationale définissant les codes pays à 2 lettres. Ex: FR (France), US (États-Unis), GB (Royaume-Uni)."],
    ["ISO 10383", "-", "Norme internationale définissant les Market Identifier Codes (MIC) pour les places boursières."],
    ["Bloomberg Open Symbology", "BSYM", "Initiative de Bloomberg fournissant des identifiants financiers ouverts et gratuits via l'API OpenFIGI."],
  ];
  const wsGlossary = XLSX.utils.aoa_to_sheet(glossary);
  wsGlossary["!cols"] = [{ wch: 50 }, { wch: 15 }, { wch: 120 }];
  XLSX.utils.book_append_sheet(wb, wsGlossary, "8. Glossaire");

  // ─── 9. SECTEURS ───
  const sectors = [
    ["LISTE DES SECTEURS DISPONIBLES"],
    [""],
    ["#", "Secteur", "Description"],
    ["1", "Equity", "Actions ordinaires et préférentielles"],
    ["2", "Common Stock", "Actions ordinaires cotées"],
    ["3", "Preferred Stock", "Actions préférentielles (dividende prioritaire)"],
    ["4", "Finance", "Services financiers (banques, assurances, gestion d'actifs)"],
    ["5", "Banking", "Secteur bancaire (banques de détail et d'investissement)"],
    ["6", "Insurance", "Assurance (vie, dommages, réassurance)"],
    ["7", "Asset Management", "Gestion d'actifs et fonds d'investissement"],
    ["8", "Private Equity", "Capital-investissement"],
    ["9", "Venture Capital", "Capital-risque"],
    ["10", "Hedge Fund", "Fonds spéculatifs"],
    ["11", "Import & Export", "Commerce international de biens"],
    ["12", "Trade", "Négoce et commerce de matières premières"],
    ["13", "Devise / Forex", "Marché des changes et paires de devises"],
    ["14", "Commodities", "Matières premières (or, pétrole, blé, etc.)"],
    ["15", "ETF", "Fonds indiciels cotés en bourse"],
    ["16", "ETP", "Produits cotés en bourse (ETF + ETN + ETC)"],
    ["17", "Mutual Fund", "Fonds commun de placement (OPCVM)"],
    ["18", "Bond / Fixed Income", "Obligations et titres à revenu fixe"],
    ["19", "Government Bond", "Obligations d'État (OAT, Treasuries, Bunds)"],
    ["20", "Corporate Bond", "Obligations d'entreprise"],
    ["21", "Municipal Bond", "Obligations municipales"],
    ["22", "Mortgage / MBS", "Titres adossés à des créances hypothécaires"],
    ["23", "Derivatives", "Produits dérivés (options, futures, swaps)"],
    ["24", "Options", "Contrats d'options (call/put)"],
    ["25", "Futures", "Contrats à terme standardisés"],
    ["26", "Structured Products", "Produits structurés complexes"],
    ["27", "Crypto / Digital Assets", "Cryptomonnaies et actifs numériques"],
    ["28", "Real Estate / REIT", "Immobilier coté (foncières)"],
    ["29", "Technology", "Secteur technologique"],
    ["30", "Healthcare / Pharma", "Santé, pharmacie, biotechnologies"],
    ["31", "Energy", "Énergie (pétrole, gaz, renouvelables)"],
    ["32", "Utilities", "Services publics (eau, électricité, gaz)"],
    ["33", "Industrials", "Industrie et manufacturing"],
    ["34", "Consumer Goods", "Biens de consommation"],
    ["35", "Consumer Services", "Services aux consommateurs"],
    ["36", "Telecommunications", "Télécommunications"],
    ["37", "Materials", "Matériaux et mines"],
    ["38", "Agriculture", "Agriculture et agroalimentaire"],
    ["39", "Transportation", "Transport et logistique"],
    ["40", "Aerospace & Defense", "Aéronautique et défense"],
    ["41", "Media & Entertainment", "Médias et divertissement"],
    ["42", "Education", "Éducation et formation"],
    ["43", "Index", "Indices boursiers (CAC 40, S&P 500, etc.)"],
    ["44", "Warrant", "Bons de souscription"],
    ["45", "Rights", "Droits de souscription"],
  ];
  const wsSectors = XLSX.utils.aoa_to_sheet(sectors);
  wsSectors["!cols"] = [{ wch: 5 }, { wch: 30 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, wsSectors, "9. Secteurs");

  // ─── 10. ROADMAP ───
  const roadmap = [
    ["ROADMAP — AMÉLIORATIONS FUTURES"],
    [""],
    ["Priorité", "Fonctionnalité", "Description", "Complexité"],
    ["🔴 Haute", "Landing page publique", "Page d'accueil marketing avec présentation produit et CTA inscription", "Moyenne"],
    ["🔴 Haute", "Dashboard analytique", "Graphiques de répartition par pays, secteur, devise, source", "Moyenne"],
    ["🔴 Haute", "Gestion des erreurs", "Messages utilisateur clairs, retries automatiques, état de l'API", "Faible"],
    ["🟡 Moyenne", "Prix en temps réel", "Intégrer une API de prix (Alpha Vantage, Yahoo Finance) pour les cours live", "Haute"],
    ["🟡 Moyenne", "Export PDF", "Générer des rapports PDF avec mise en page professionnelle", "Moyenne"],
    ["🟡 Moyenne", "Rôles utilisateurs", "Admin, analyste, lecteur — avec permissions différenciées", "Haute"],
    ["🟡 Moyenne", "Import fichier CSV/Excel", "Uploader un fichier pour enrichir en masse les identifiants", "Moyenne"],
    ["🟢 Basse", "API REST publique", "Exposer un endpoint pour intégration tierce", "Haute"],
    ["🟢 Basse", "Historique des modifications", "Audit trail des changements sur les actifs", "Moyenne"],
    ["🟢 Basse", "Alertes personnalisées", "Notifications configurables (nouveau secteur, nouveau pays, etc.)", "Moyenne"],
    ["🟢 Basse", "Multi-langue", "Interface en anglais, français, espagnol", "Faible"],
    ["🟢 Basse", "Application mobile", "Version PWA ou React Native", "Haute"],
  ];
  const wsRoadmap = XLSX.utils.aoa_to_sheet(roadmap);
  wsRoadmap["!cols"] = [{ wch: 15 }, { wch: 28 }, { wch: 65 }, { wch: 12 }];
  XLSX.utils.book_append_sheet(wb, wsRoadmap, "10. Roadmap");

  // Generate and download
  XLSX.writeFile(wb, "Cahier_Projet_Data_Enricher_Financier.xlsx");
}
